# Usage: docker compose up -d

services:

  gres:
    image: ghcr.io/stefanofoti/gres:latest
    container_name: gres
    deploy:
      replicas: 1
    #dns: # If resolving issues occur, you can add public DNS servers here
    #  - 8.8.8.8
    #  - 1.1.1.1
    volumes:
      - gres_data:/app/data
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      HA_REFRESH_INTERVAL_SEC: ${HA_REFRESH_INTERVAL_SEC:-15}
    networks:
      - gres-network

networks:
  gres-network:
    driver: bridge

volumes:
  gres_data: